# institution.group
# institution.group.[device_type]

[brown.sheinberg]
wifi_country=US
timezone=America/New_York
locale=en_us
default_subgroup=incage
ess_source=https://github.com/homebase-sheinberg/ess.git
mesh_host=https://dserv.net
mesh_workgroup=brown-sheinberg
cloud_data_store=yes
cloud_registry=https://ngage.systems/create_mysql_entity_user.php
cloud_ingest=https://ngage.systems/ingest.php

[brown.sheinberg.incage]
username=lab
monitor_width_cm=21.7
monitor_height_cm=13.6
monitor_distance_cm=30.0
screen_pixels_width=1280
screen_pixels_height=800
screen_refresh_rate=60
screen_rotation=180

[brown.sheinberg.booth]
username=lab
monitor_width_cm=50
monitor_height_cm=30
monitor_distance_cm=70
screen_pixels_width=1920
screen_pixels_height=1080
screen_refresh_rate=100
screen_rotation=0

[brown.desrochers]
wifi_country=US
timezone=America/New_York
locale=en_us
default_subgroup=incage
ess_source=https://github.com/homebase-sheinberg/ess.git
mesh_host=https://dserv.net
mesh_workgroup=brown-desrochers
cloud_data_store=yes
cloud_registry=https://ngage.systems/create_mysql_entity_user.php
cloud_ingest=https://ngage.systems/ingest.php


[brown.desrochers.incage]
username=lab
monitor_width_cm=21.7
monitor_height_cm=13.6
monitor_distance_cm=30.0
screen_pixels_width=1280
screen_pixels_height=800
screen_refresh_rate=60
screen_rotation=180

[brown.desrochers.booth]
username=lab
monitor_width_cm=50
monitor_height_cm=30
monitor_distance_cm=70
screen_pixels_width=1920
screen_pixels_height=1080
screen_refresh_rate=100
screen_rotation=0


[jhu.monosov]
wifi_country=US
timezone=America/New_York
locale=en_us
default_subgroup=incage
ess_source=https://github.com/homebase-sheinberg/ess.git
mesh_host=https://dserv.net
mesh_workgroup=jhu.monosov
cloud_data_store=yes
cloud_registry=https://ngage.systems/create_mysql_entity_user.php
cloud_ingest=https://ngage.systems/ingest.php

[jhu.monosov.incage]
username=lab
monitor_width_cm=21.7
monitor_height_cm=13.6
monitor_distance_cm=30.0
screen_pixels_width=1280
screen_pixels_height=800
screen_refresh_rate=60
screen_rotation=180


[stanford.moore]
wifi_country=US
timezone=America/Los_Angeles
locale=en_us
default_subgroup=incage
ess_source=https://github.com/homebase-sheinberg/ess.git
mesh_host=https://dserv.net
mesh_workgroup=stanford.moore
cloud_data_store=yes
cloud_registry=https://ngage.systems/create_mysql_entity_user.php
cloud_ingest=https://ngage.systems/ingest.php

[stanford.moore.incage]
username=lab
monitor_width_cm=21.7
monitor_height_cm=13.6
monitor_distance_cm=30.0
screen_pixels_width=1280
screen_pixels_height=800
screen_refresh_rate=60
screen_rotation=180

